Repository justvinny/sdp-team-doctor-hu, pull requests merged in 2021-10, with the labels that each got.

#21 Jacob - Profile Picture for Staff & Patients
  App.js
  components/login/SignInScreen.js
  components/login/WelcomeScreen.js
  components/mainmenu/Menu.js
  components/profile/ProfileSelection.js
  components/profile/patient/AddressTab.js
  components/profile/patient/MedicalTab.js
  components/profile/patient/PatientProfile.js
  components/profile/patient/ProfileTab.js
  components/profile/profilecomponents/BottomSheetNav.js
  components/profile/profilecomponents/FloatingActionButton.js
  components/profile/profilecomponents/GlobalProfileTab.js
  components/profile/profilecomponents/TabStyles.js
  components/profile/profilecomponents/UploadProfilePicture.js
  components/profile/staff/AboutTab.js
  components/profile/staff/ProfileTab.js
  components/profile/staff/StaffProfile.js
  firebase/firebaseConfig.js
  firebase/firestoreService.js
  models/Patient.js
  models/Staff.js
  models/User.js
  package-lock.json
  package.json
Labels: enhancement, iOS, Android

#27 Vinson comments feature
  App.js
  components/documentUpload/UploadDocument.js
  components/documentUpload/UploadDocumentButton.js
  components/mainmenu/Menu.js
  components/notifications/NotificationListItem.js
  components/notifications/NotificationScreenController.js
  components/profile/comments/CommentActions.js
  components/profile/comments/CommentBox.js
  components/profile/comments/CommentCard.js
  components/profile/comments/CommentOverlay.js
  components/profile/comments/CommentReplies.js
  components/profile/comments/CommentReplyBox.js
  components/profile/comments/CommentScreenController.js
  components/profile/comments/CommentScreenView.js
  components/profile/comments/CommentTabNavigation.js
  components/profile/comments/PrivateCommentTab.js
  components/profile/comments/PublicCommentTab.js
  components/profile/patient/FloatingMenu.js
  components/profile/patient/PatientProfile.js
  components/profile/profilecomponents/BottomSheetNav.js
  components/profile/profilecomponents/UploadProfilePicture.js
  components/settings/ChangePasswordScreen.js
  firebase/firestoreService.js
  package-lock.json
Labels: iOS, Android

#28 Updated Profiles for Staff & Patient
  App.js
  components/profile/ProfileSelection.js
  components/profile/comments/CommentActions.js
  components/profile/comments/CommentBox.js
  components/profile/comments/CommentOverlay.js
  components/profile/patient/MedicalTab.js
  components/profile/patient/PatientProfileController.js
  components/profile/patient/PatientProfileView.js
  components/profile/profilecomponents/FloatingActionButton.js
  components/profile/profilecomponents/ProfileInformation.js
  components/profile/profilecomponents/profilePicture/ProfilePicture.js
  components/profile/profilecomponents/profilePicture/UploadProfilePictureController.js
  components/profile/profilecomponents/profilePicture/UploadProfilePictureView.js
  components/profile/profilecomponents/styles/TabStyles.js
  components/profile/profilecomponents/styles/TextInputStyles.js
  components/profile/staff/AboutTab.js
  components/profile/staff/StaffProfile.js
  components/profile/staff/StaffProfileController.js
  components/profile/staff/StaffProfileView.js
  components/search/SearchUserCard.js
Labels: iOS, Android

#32 Changed default filter to both instead of staff for user staff.
  components/mainmenu/Menu.js
  components/search/SearchUserScreenController.js
  components/search/filter/FilterModal.js
Labels: Android

#29 Doc Upload Fix and Web View modification
  components/documentUpload/UploadDocument.js
  components/documentUpload/ViewDocument.js
Labels: Android

#39 Document view update catie
  components/documentUpload/viewSingleDocument/ViewDocumentController.js
  components/documentUpload/viewSingleDocument/ViewDocumentView.js
Labels: iOS, Android
